USE [master]
GO
CREATE LOGIN [George] WITH PASSWORD=N'password1', DEFAULT_DATABASE=[ShopHere], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [ShopHere]
GO
CREATE USER [George] FOR LOGIN [George]
GO
ALTER ROLE [db_owner] ADD MEMBER [George]
GO

USE [master]
GO
CREATE LOGIN [John] WITH PASSWORD=N'password2', DEFAULT_DATABASE=[ShopHere], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [ShopHere]
GO
CREATE USER [John] FOR LOGIN [John]
GO
ALTER ROLE [db_datareader] ADD MEMBER [John]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [John]
GO

USE [master]
GO
CREATE LOGIN [Sara] WITH PASSWORD=N'password3', DEFAULT_DATABASE=[ShopHere], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [ShopHere]
GO
CREATE USER [Sara] FOR LOGIN [Sara]
GO
ALTER ROLE [db_datareader] ADD MEMBER [Sara]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [Sara]
GO